version: '3.8'

services:
  # Coordinator - Central manager for the system
  coordinator:
    build:
      context: .
      dockerfile: docker/coordinator/Dockerfile
    ports:
      - "8000:8000"  # API port
    environment:
      - RABBITMQ_HOST=rabbitmq
      - NEO4J_URI=bolt://neo4j:7687
      - MONGODB_URI=mongodb://mongodb:27017/
      - LOG_LEVEL=INFO
    depends_on:
      - rabbitmq
      - neo4j
      - mongodb
    volumes:
      - ./coordinator/config.yml:/app/coordinator/config.yml
    networks:
      - knowledge_network

  # Message Broker - Communication between components  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - knowledge_network

  # Graph Database - Knowledge graph storage
  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"  # HTTP port
      - "7687:7687"  # Bolt port
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - knowledge_network

  # Document Database - Content storage
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - knowledge_network

  # Scraper Agent - Content extraction
  scraper_agent:
    build:
      context: .
      dockerfile: docker/agents/scraper/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MONGODB_URI=mongodb://mongodb:27017/
      - AGENT_ID=scraper-1
      - LOG_LEVEL=INFO
    depends_on:
      - coordinator
      - rabbitmq
      - mongodb
    networks:
      - knowledge_network

  # Processor Agent - Content analysis
  processor_agent:
    build:
      context: .
      dockerfile: docker/agents/processor/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MONGODB_URI=mongodb://mongodb:27017/
      - NEO4J_URI=bolt://neo4j:7687
      - AGENT_ID=processor-1
      - LOG_LEVEL=INFO
    depends_on:
      - coordinator
      - rabbitmq
      - mongodb
      - neo4j
    networks:
      - knowledge_network

  # Knowledge Agent - Knowledge graph management
  knowledge_agent:
    build:
      context: .
      dockerfile: docker/agents/knowledge/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - NEO4J_URI=bolt://neo4j:7687
      - AGENT_ID=knowledge-1
      - LOG_LEVEL=INFO
    depends_on:
      - coordinator
      - rabbitmq
      - neo4j
    networks:
      - knowledge_network

  # Learning Agent - Learning and enhancement
  learning_agent:
    build:
      context: .
      dockerfile: docker/agents/learning/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MONGODB_URI=mongodb://mongodb:27017/
      - NEO4J_URI=bolt://neo4j:7687
      - AGENT_ID=learning-1
      - LOG_LEVEL=INFO
    depends_on:
      - coordinator
      - rabbitmq
      - mongodb
      - neo4j
    networks:
      - knowledge_network

  # UI Agent - API and WebSocket server
  ui_agent:
    build:
      context: .
      dockerfile: docker/agents/ui/Dockerfile
    ports:
      - "3100:3100"  # API and WebSocket port
    environment:
      - RABBITMQ_HOST=rabbitmq
      - NEO4J_URI=bolt://neo4j:7687
      - MONGODB_URI=mongodb://mongodb:27017/
      - AGENT_ID=ui-1
      - LOG_LEVEL=INFO
      - PORT=3100
      - HOST=0.0.0.0
    depends_on:
      - coordinator
      - rabbitmq
      - neo4j
      - mongodb
    networks:
      - knowledge_network

  # Frontend - Web UI
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://ui_agent:3100
      - NEXT_PUBLIC_WEBSOCKET_URL=http://ui_agent:3100
    depends_on:
      - ui_agent
    networks:
      - knowledge_network

volumes:
  neo4j_data:
  neo4j_logs:
  mongodb_data:
  rabbitmq_data:

networks:
  knowledge_network:
    driver: bridge 